export const PULL_G2A_PRODUCTS = 'PULL_G2A_PRODUCTS';
export const ASYNC_UPDATE_START = 'ASYNC_UPDATE_START';
export const ASYNC_UPDATE_COMPLETE = 'ASYNC_UPDATE_COMPLETE';
export const PLACE_ORDER = 'PLACE_ORDER';
export const PULL_ORDER_STATUS = 'PULL_ORDER_STATUS';
export const PAY_ORDER = 'PAY_ORDER';
export const GET_PRODUCT_KEY = 'GET_PRODUCT_KEY';

